#!/usr/bin/env python3
"""Merge assets/manifest/*.json fragments into assets/manifest.js.

    python3 tools/build_manifest.py                 # writes assets/manifest.js
    python3 tools/build_manifest.py --check         # exit 1 if assets/manifest.js is stale
    python3 tools/build_manifest.py --out PATH      # write (or --check) PATH instead

Output is deterministic (fragments merged in filename order, keys sorted) and is a classic script
(`window.ASSET_MANIFEST = {...};`) so the game also works from file:// without fetch().
Every `src` / `srcBlur` path that exists gets a content hash, `path?v=<sha1[:10]>`, so the service worker's
cache-first image cache never serves a changed image stale (and `--check` also flags images changed without a
rebuild). Missing files stay bare (the game then draws a placeholder). The fragments themselves are not modified.
Works with zero fragments (-> `window.ASSET_MANIFEST = {};`). Standard library only.
"""
from __future__ import annotations

import copy
import hashlib
import json
import os
import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
FRAG_DIR = ROOT / "assets" / "manifest"
OUT = ROOT / "assets" / "manifest.js"


def deep_merge(dst: dict, src: dict, where: str = "") -> dict:
    for key, val in src.items():
        if key in dst and isinstance(dst[key], dict) and isinstance(val, dict):
            deep_merge(dst[key], val, f"{where}.{key}")
        else:
            if key in dst and dst[key] != val:
                print(f"build_manifest: warning: {where}.{key} overridden by a later fragment", file=sys.stderr)
            dst[key] = val
    return dst


def collect_paths(node, out: list):
    """Bare image paths (anything after '?' stripped) referenced by src / srcBlur keys."""
    if isinstance(node, dict):
        for k, v in node.items():
            if k in ("src", "srcBlur") and isinstance(v, str):
                out.append(v.split("?")[0])
            else:
                collect_paths(v, out)
    elif isinstance(node, list):
        for v in node:
            collect_paths(v, out)


def with_hashes(node):
    """Deep copy of `node` with every existing src / srcBlur file rewritten to `path?v=<content hash>`."""
    node = copy.deepcopy(node)

    def walk(n):
        if isinstance(n, dict):
            for k, v in n.items():
                if k in ("src", "srcBlur") and isinstance(v, str):
                    p = v.split("?")[0]
                    f = ROOT / p
                    n[k] = f"{p}?v={hashlib.sha1(f.read_bytes()).hexdigest()[:10]}" if f.is_file() else p
                else:
                    walk(v)
        elif isinstance(n, list):
            for v in n:
                walk(v)

    walk(node)
    return node


def build() -> tuple[str, dict, list]:
    merged: dict = {}
    fragments = sorted(FRAG_DIR.glob("*.json")) if FRAG_DIR.is_dir() else []
    for frag in fragments:
        try:
            data = json.loads(frag.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"build_manifest: skipping {frag.name}: {exc}", file=sys.stderr)
            continue
        if not isinstance(data, dict):
            print(f"build_manifest: skipping {frag.name}: top level must be an object", file=sys.stderr)
            continue
        deep_merge(merged, data, frag.stem)
    body = json.dumps(with_hashes(merged), sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    text = (
        "/* GENERATED by tools/build_manifest.py from assets/manifest/*.json — do not edit by hand. */\n"
        f"window.ASSET_MANIFEST = {body};\n"
    )
    return text, merged, fragments


def show(path: pathlib.Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def main(argv: list[str]) -> int:
    out = OUT
    if "--out" in argv:
        i = argv.index("--out")
        if i + 1 >= len(argv):
            print("build_manifest: --out needs a path", file=sys.stderr)
            return 2
        out = pathlib.Path(argv[i + 1]).resolve()
    text, merged, fragments = build()
    paths: list = []
    collect_paths(merged, paths)
    missing = [p for p in paths if not (ROOT / p).is_file()]
    for p in missing:
        print(f"build_manifest: warning: referenced file missing: {p}", file=sys.stderr)
    if "--check" in argv:
        if out.is_file() and out.stat().st_mode & 0o044 != 0o044:
            print(f"build_manifest: warning: {show(out)} is not world-readable "
                  f"(mode {out.stat().st_mode & 0o777:04o}); rebuild it or chmod 644", file=sys.stderr)
        current = out.read_text(encoding="utf-8") if out.is_file() else None
        if current != text:
            print(f"build_manifest: {show(out)} is stale", file=sys.stderr)
            return 1
        print("build_manifest: up to date")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".manifest.", suffix=".js", dir=str(out.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        # mkstemp creates 0600: give the output normal permissions (0644 under umask 022) before it replaces OUT
        mask = os.umask(0)
        os.umask(mask)
        os.chmod(tmp, 0o666 & ~mask)
        os.replace(tmp, out)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    groups = ", ".join(sorted(merged)) or "none"
    print(f"build_manifest: {len(fragments)} fragment(s) -> {show(out)} (groups: {groups}; {len(paths)} files, {len(missing)} missing)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
